image: docker:20.10.16

variables:
  # When you use the dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. Docker 19.03 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
  #
  # Specify to Docker where to create the certificates. Docker
  # creates them automatically on boot, and creates
  # `/certs/client` to share between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

before_script:
  - docker info
  - docker pull phildue/vslam:dev
  - docker tag phildue/vslam:dev vslam:dev

build:
  stage: build
  script:
    
    - docker build -t vslam:dev --target developer .
    - docker build -t vslam:builder --target builder .
    - docker build -t vslam:runtime --target runtime .
test:
  stage: test
  script:
    - docker run vslam:builder /bin/bash -c "colcon test --event-handler console_direct+ ; colcon test-result"

evaluate:
  stage: test
  script: 
    - docker run -v/mnt/dataset:/mnt/dataset vslam:runtime /bin/bash -c "source local_setup.bash && python3 /script/evaluate.py ci-evaluation rgbd_dataset_freiburg1_desk --run_algo --commit_hash $CI_COMMIT_SHA --out_root /home/ros/"

lint:
  stage: test
  script:
    - docker run vslam:builder ament_clang_format --xunit-file build/vslam_ros/test_results/vslam_ros/clang_format.xunit.xml"
    - docker run vslam:builder ament_clang_tidy --xunit-file build/vslam_ros/test_results/vslam_ros/clang_tidy.xunit.xml"
    - docker run vslam:builder ament_flake8 --xunit-file build/vslam_ros/test_results/vslam_ros/flake8.xunit.xml"

deploy-container:
  stage: deploy
  script:
    - docker tag vslam:dev phildue/vslam:dev
    - docker push phildue/vslam:dev
    - docker tag vslam:dev phildue/vslam:runtime
    - docker push phildue/vslam:runtime
